# Generated by Django 4.1.5 on 2024-06-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
