# Generated by Django 4.1.5 on 2024-06-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_canceled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="canceled",
            new_name="cancelled",
        ),
    ]
