# Generated by Django 4.1.5 on 2024-02-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='placeholder description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
