# Generated by Django 4.1.5 on 2024-02-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_description_alter_event_email_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='title placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
