# Generated by Django 4.1.5 on 2024-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_establishments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='establishments',
            new_name='establishment_type',
        ),
        migrations.AddField(
            model_name='event',
            name='particular_eateries',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
