# Generated by Django 4.1.5 on 2024-02-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_establishments_event_establishment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_title',
        ),
    ]
