# Generated by Django 4.1.5 on 2024-03-23 06:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_title_event_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='establishment_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cafes', 'Cafes'), ('Restaurants', 'Restaurants'), ('Bars', 'Bars'), ('Clubs', 'Clubs')], max_length=20, null=True),
        ),
    ]
