# Generated by Django 4.1.5 on 2024-03-23 06:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_event_establishment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='establishment_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cafes', 'cafes'), ('Restaurants', 'restaurants'), ('Bars', 'bars'), ('Clubs', 'clubs')], max_length=200, null=True),
        ),
    ]
