# Generated by Django 4.1.5 on 2024-05-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_event_guests_event_location_alter_event_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(null=True, verbose_name='Event Date and Time'),
        ),
    ]
