# Generated by Django 4.1.5 on 2024-05-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
