# Generated by Django 4.1.5 on 2024-05-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('messager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messager', to='app.profile')),
                ('messaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging', to='app.profile')),
            ],
        ),
    ]
