# Generated by Django 4.1.5 on 2024-05-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messaging',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messager',
            new_name='sender',
        ),
    ]
