# Generated by Django 4.1.5 on 2024-05-12 00:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='establishment_type',
        ),
        migrations.AddField(
            model_name='event',
            name='event_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SPORTING', 'Sporting'), ('ENTERTAINMENT', 'Entertainment'), ('FOOD AND BEVERAGE', 'Food and Beverage'), ('NIGHTLIFE', 'Nightlife'), ('NETWORKING', 'Networking')], max_length=200, null=True),
        ),
    ]
