# Generated by Django 4.1.5 on 2024-05-12 01:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_event_establishment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendees',
            new_name='total_attendees',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SPORTING / OUTDOOR', 'Sporting / Outdoor'), ('ENTERTAINMENT', 'Entertainment'), ('FOOD AND BEVERAGE', 'Food and Beverage'), ('NIGHTLIFE', 'Nightlife'), ('OTHER', 'Other')], max_length=200, null=True),
        ),
    ]
