# Generated by Django 4.1.5 on 2024-05-14 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_attendees_event_total_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 2, 46, 9, 992751, tzinfo=datetime.timezone.utc)),
        ),
    ]
