# Generated by Django 4.1.5 on 2024-05-23 07:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True, verbose_name='Time Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SPORTING / OUTDOOR', 'Sporting / Outdoor'), ('ENTERTAINMENT', 'Entertainment'), ('FOOD AND BEVERAGE', 'Food and Beverage'), ('NIGHTLIFE', 'Nightlife'), ('OTHER', 'Other')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
