# Generated by Django 4.1.5 on 2024-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_event_event_datetime_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
