# Generated by Django 4.1.5 on 2024-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gallery_image1',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='gallery_image2',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='gallery_image3',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to=''),
        ),
    ]
