# Generated by Django 4.1.5 on 2024-05-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_profile_gallery_image1_profile_gallery_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_categories',
        ),
    ]
