# Generated by Django 4.1.5 on 2024-05-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_event_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gallery_image1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gallery_image2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gallery_image3',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
