# Generated by Django 4.1.5 on 2024-05-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
