# Generated by Django 4.1.5 on 2024-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_remove_event_guests_remove_event_host_delete_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friend_visibility",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
