# Generated by Django 4.1.5 on 2024-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_profile_friend_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_25", "Under 25"),
                    ("25_to_35", "25 - 35"),
                    ("36_and_over", "36 and over"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
