# Generated by Django 4.1.5 on 2024-06-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_profile_age_band"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rather_not_say", "Rather not say"),
                    ("under_25", "Under 25"),
                    ("25_to_35", "25 - 35"),
                    ("36_and_over", "36 and over"),
                ],
                default="rather_not_say",
                max_length=20,
                null=True,
            ),
        ),
    ]
