# Generated by Django 4.1.5 on 2024-06-03 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_profile_friend_visibility"),
        ("photos", "0004_rename_category_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.profile",
            ),
        ),
    ]
