# Generated by Django 4.1.5 on 2024-06-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0005_album_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="category",
            new_name="album",
        ),
    ]
