# Generated by Django 4.1.5 on 2024-06-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
    ]
