# Generated by Django 4.1.5 on 2024-06-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_profile_friend_visibility"),
        ("direct_messages", "0003_conversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="direct_messages.conversation",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_statuses",
                        to="app.profile",
                    ),
                ),
            ],
        ),
    ]
